-- this is first creating a table that has 4 columns
-- the IF NOT EXISTS prevents the CREATE TABLE being attempted when the table already exists

CREATE TABLE IF NOT EXISTS whopipe_video_views (
    view_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    video_name TEXT NOT NULL,
    region TEXT NOT NULL,
    date_viewed TIMESTAMP DEFAULT now() NOT NULL
);

--this transaction and the third one create a new type called department which is an ENUM (enum is a list of options that may be used by columns (which have this new type) in table rows)
--CREATE TYPE doesnt support IF NOT EXISTS; instead remove the type if it does exist first

DROP TYPE IF EXISTS department;
CREATE TYPE department AS ENUM (
    'Electronics',
    'Cleaning',
    'Grocery',
    'Furniture',
    'Stationery',
    'Clothing',
    'DIY',
    'Sports',
    'Homeware',
    'Games',
    'Transport'
);

--this is to create a table that has 4 columns. price column is set to decimal which can be 12 in "precision" and 2 decimal points
--when inserting rows into this table, their value for category needs to be one of those listed in the ENUM for department

CREATE TABLE IF NOT EXISTS amazong_products (
    product_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    price decimal(12,2) NOT NULL,
    image TEXT,
    category department NOT NULL
);