DROP TYPE IF EXISTS category;
CREATE TYPE category AS ENUM (
    'Main',
    'Snack',
    'Lunch',
    'Breakfast'
);


CREATE TABLE IF NOT EXISTS shopping_list (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    price DECIMAL(8,6) NOT NULL,
    date_added TIMESTAMP DEFAULT now() NOT NULL,
    checked BOOLEAN DEFAULT false,
    category grocery NOT NULL
);

